/*
 * Copyright (C) 2015 L00131070.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package project_year4.gui;

/**
 *
 * @author L00131070
 */
public class DisplayMaze extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMaze
     */
    public DisplayMaze() {
        initComponents();
        for (int i = 0; i < 31; i++) {
            for (int j = 0; j < 31; j++) {
                if ((i % 2) == 0 && (j % 2) == 0) {
                    add(new DisplayGridCell(j / 2 + "/" + (31-i) / 2));
                } else if ((i % 2) == 1 && (j % 2) == 1) {
                    add(new DisplayWallCell(""));
                } else {
                    add(new DisplayNode("-1"));
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 102, 0));
        setLayout(new java.awt.GridLayout(31, 31, 2, 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
