/*
 * Copyright (C) 2015 L00131070.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package project_year4.gui;

import java.awt.Dimension;
import java.awt.GridLayout;

/**
 *
 * @author L00131070
 */
public class DisplayMaze1 extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMaze1
     */
    public DisplayMaze1() {
        int mazesize = 16;
        initComponents();
        for (int i = 0; i < mazesize; i++) {
            for (int j = 0; j < mazesize; j++) {
                jPanel1.add(new DisplayGridCell(j + "/" + (mazesize - 1 - i)));
                if (j < (mazesize - 1)) {
                    jPanel2.add(new DisplayNode("-1",DisplayNode.NodeTyp.X));
                }
                if (i < (mazesize - 1)) {
                    jPanel3.add(new DisplayNode("-1", DisplayNode.NodeTyp.Y));
                }
            }
        }
        ((GridLayout) jPanel1.getLayout()).setColumns(mazesize);
        ((GridLayout) jPanel1.getLayout()).setRows(mazesize);
        Dimension dim = new Dimension(mazesize * DisplayGridCell.CELLSIZE, mazesize * DisplayGridCell.CELLSIZE);
        System.out.println("size: " + dim + " size: " + DisplayGridCell.CELLSIZE);
        jLayeredPane1.setSize(dim);
        jLayeredPane1.setPreferredSize(dim);
        jPanel1.setPreferredSize(dim);
        jPanel2.setPreferredSize(new Dimension((mazesize-1) * DisplayGridCell.CELLSIZE, mazesize * DisplayGridCell.CELLSIZE));
        jPanel3.setPreferredSize(new Dimension((mazesize) * DisplayGridCell.CELLSIZE, (mazesize-1) * DisplayGridCell.CELLSIZE));
//        jPanel2.setLocation(25,0);
        System.out.println("gridnode pref. size: " + jLayeredPane1.getPreferredSize());
        System.out.println("gridnode size: " + jLayeredPane1.getSize());
        System.out.println("P1: "+jPanel1.getPreferredSize()+" "+jPanel1.getLocation());
        System.out.println("P2: "+jPanel2.getPreferredSize()+" "+jPanel2.getLocation());
        System.out.println("P3: "+jPanel3.getPreferredSize()+" "+jPanel3.getLocation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.GridLayout(16, 16, 2, 2));
        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 0));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 400));
        jPanel2.setLayout(new java.awt.GridLayout(16, 15, 2, 2));
        jLayeredPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.MODAL_LAYER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(15, 16, 0, 13));
        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, -1, -1));
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.MODAL_LAYER);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
